name: emt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.2
  - requests>=2.31
  - streamlit>=1.35
  - python-dotenv>=1.0
  - numpy>=1.26
  - scipy>=1.13
  - matplotlib>=3.9
  - scikit-learn>=1.5
  - statsmodels>=0.14
  - lightgbm>=4.3
  - xgboost>=2.0
  - tslearn>=0.6
  - arch>=6.3
  - hmmlearn>=0.3
  - pip
  - pip:
      - prophet>=1.1
      - pymc3>=3.11
      - causalimpact>=0.4
